# apiVersion: v1
# kind: Pod
# metadata:
#   name: rabbitmq-consumer-pod
# spec:
#   containers:
#   - name: consumer-container
#     image: node:18
#     command:
#     - "/bin/sh"
#     - "-c"
#     - |
#       cd /app
#       npm i
#       node consumer.js
#     volumeMounts:
#     - name: app-code
#       mountPath: /app
#     envFrom:
#     - configMapRef:
#         name: rabbitmq-config-env
#   volumes:
#   - name: app-code
#     hostPath:
#       # docker-desktop producer directory's path on WSL
#       path:  /run/desktop/mnt/host/wsl/consumer
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-consumer-pod
  labels:
    app: rabbitmq-client-pod
spec:
  containers:
  - name: consumer-container
    image: node:18
    command:
    - "/bin/sh"
    - "-c"
    - |
      cd /app
      npm i
      node client.js
    volumeMounts:
    - name: app-code
      mountPath: /app
    envFrom:
    - configMapRef:
        name: rabbitmq-config-env
  volumes:
  - name: app-code
    hostPath:
      # docker-desktop producer directory's path on WSL
      path:  /run/desktop/mnt/host/wsl/consumer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
